const products = [
    { id: 1, name: "Premium Designer 24pcs Stick-on Nails set", category: "1", price: "₹299", image: "/nails/Premium Designer 24pcs Stick-on Nails set.jpg", link: "https://amzn.to/3RB6CoH" },
    { id: 1, name: "acrylic translucent press on nails artifical designer 3D", category: "1", price: "₹401", image: "/nails/acrylic translucent press on nails artifical designer 3D.jpg", link: "https://amzn.to/4clOwR5" },
    { id: 1, name: "LIARTY 480Pcs French Fake Nails", category: "1", price: "₹3453", image: "/nails/LIARTY 480Pcs French Fake Nails.jpg", link: "https://amzn.to/3G0e7mH" },
    { id: 1, name: "Elegant Red Nails", category: "1", price: "$3.5", image: "/nails/Elegant Red Nails.jpg", link: "https://amzn.to/3DYkoi5" },
    { id: 2, name: "Luxury Gold Nails", category: "2", price: "$3.1", image: "/nails/Luxury Gold Nails.jpg", link: "https://amzn.to/4iNEKdd" },
    { id: 3, name: "Classic French Nails", category: "3", price: "$4", image: "/nails/Classic French Nails.jpg", link: "https://amzn.to/4hMuvnT" },
    { id: 4, name: "Glitter Glam Nails", category: "3", price: "$2.9", image: "/nails/Glitter Glam Nails.jpg", link: "https://amzn.to/3QVXXgn" },
    { id: 5, name: "Ombre Pink Nails", category: "4", price: "$2.5", image: "/nails/Ombre Pink Nails.jpg", link: "https://amzn.to/3Rtscve" },
    { id: 6, name: "Acrylic Nails", category: "4", price: "$2.5", image: "/nails/Acrylic Nails.jpg", link: "https://amzn.to/3Rs0PSh" },
    { id: 7, name: "French Nails", category: "4", price: "$2.5", image: "/nails/French Nails.jpg", link: "https://amzn.to/3XDWMG7" },
    { id: 8, name: "Matte Green Shadeand", category: "4", price: "$2.5", image: "/nails/matte green shadeand.jpg", link: "https://amzn.to/4hYqFIC" },
    { id: 9, name: "Gel Nails", category: "4", price: "$2.5", image: "/nails/Gel Nails.jpg", link: "https://amzn.to/4hTWnGP" },
    { id: 10, name: "Ombre Nails", category: "4", price: "$2.5", image: "/nails/Ombre Nails.jpg", link: "https://amzn.to/4hV9dEG" },
    { id: 11, name: "Dark Emerald Green Nail Designs", category: "1", price: "$3.5", image: "/nails/Dark Emerald Green Nail Designs.jpg", link: "https://amzn.to/3DYkoi5" },
    { id: 12, name: "Gorgeous Green and Gold Nails", category: "2", price: "$3.1", image: "/nails/Gorgeous Green and Gold Nails.jpg", link: "https://amzn.to/4iNEKdd" },
    { id: 13, name: "25 Adorable Easter Nail Designs for Spring 2025", category: "3", price: "$4", image: "/nails/25 Adorable Easter Nail Designs for Spring 2025.jpg", link: "https://amzn.to/4hMuvnT" },
    { id: 14, name: "Spring nails", category: "3", price: "$2.9", image: "/nails/Spring nails.jpg", link: "https://amzn.to/41V14LX" },
    { id: 15, name: "Chocolate Brown Nails", category: "4", price: "$2.5", image: "/nails/Chocolate Brown Nails.jpg", link: "https://amzn.to/42pIHyL" },
    { id: 16, name: "Red Nail Design", category: "4", price: "$2.5", image: "/nails/Red Nail Design.jpg", link: "https://amzn.to/3Rs0PSh" },
    { id: 17, name: "winter nail design", category: "4", price: "$2.5", image: "/nails/winter nail design.jpg", link: "https://amzn.to/3XDWMG7" },
    { id: 18, name: "Chic and Elegant Nail Art", category: "4", price: "$5", image: "/nails/Chic and Elegant Nail Art.jpg", link: "https://amzn.to/3Rs0PSh" },
    { id: 19, name: "Navy Blue Fall Nail", category: "4", price: "$3.5", image: "/nails/Navy Blue Fall Nail.jpg", link: "https://amzn.to/4hYqFIC" },
    { id: 20, name: "Tiny Little Artworks", category: "2", price: "$3.1", image: "/nails/Tiny Little Artworks.jpg", link: "https://amzn.to/4iNEKdd" },
    { id: 21, name: "Pink Nails", category: "3", price: "$3.9", image: "/nails/Pink Nails.jpg", link: "https://amzn.to/3QVXXgn" },
    { id: 22, name: "Matte Green Nails", category: "2", price: "$39.9", image: "/nails/Matte Green Nails.jpg", link: "https://amzn.to/4cdQrY9" },
    { id: 23, name: "Matte Ombre Purple Spring Nails 2025", category: "3", price: "$33.9", image: "/nails/Matte Ombre Purple Spring Nails 2025.jpg", link: "https://amzn.to/4ci6TGD" },
    { id: 24, name: "Coffin nails designs", category: "1", price: "$23.9", image: "/nails/Coffin nails designs.jpg", link: "https://amzn.to/4ci6TGD" },
    { id: 25, name: "Christmas Nails and Fall Nails", category: "2", price: "$23.9", image: "/nails/Christmas Nails and Fall Nails.jpg", link: "https://amzn.to/4ci6TGD" },
    { id: 26, name: "Matte grey Nails with Gold Stripes", category: "3", price: "$33.9", image: "/nails/Matte grey Nails with Gold Stripes.jpg", link: "https://amzn.to/4ci6TGD" },

];

export default products;
